services:
  - type: web
    name: nerou-finder
    runtime: node
    plan: starter
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    disk:
      name: uploads
      mountPath: /opt/render/project/src/assets/uploads
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_URL
        sync: false
